version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: richmond-dms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: dms_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: richmond-dms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_MODE: ${NEXT_PUBLIC_APP_MODE:-production}
        NEXT_PUBLIC_ENABLE_LOGIN: ${NEXT_PUBLIC_ENABLE_LOGIN:-true}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:4000}
        NEXT_PUBLIC_COMPANY_NAME: ${NEXT_PUBLIC_COMPANY_NAME:-Richmond DMS}
        NEXT_PUBLIC_COMPANY_LOCATION: ${NEXT_PUBLIC_COMPANY_LOCATION:-Richmond, VA}
    image: eakarsun4/richmond-dms:latest
    container_name: richmond-dms-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.aws
    environment:
      # Database Configuration
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-changeme}@postgres:5432/dms_dev
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: dms_dev

      # Redis Configuration
      REDIS_URL: redis://redis:6379

      # JWT Secrets (CHANGE THESE IN PRODUCTION!)
      JWT_SECRET: ${JWT_SECRET:-your_secret_key_change_in_production}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-your_refresh_secret_change_in_production}

      # Application Configuration
      NODE_ENV: production
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
      BACKEND_URL: ${BACKEND_URL:-http://localhost:4000}

      # AWS Configuration (optional)
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

      # Storage Configuration
      STORAGE_TYPE: ${STORAGE_TYPE:-filesystem}
      # For S3: set STORAGE_TYPE=s3 and provide S3_BUCKET_NAME
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}

    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - app_uploads:/app/uploads
      - app_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local
